vich_uploader:
    db_driver: orm

    mappings:
        deals_images:
            uri_prefix: /uploads/images/deals
            upload_destination: '%kernel.project_dir%/public/uploads/images/deals'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
